### ISSUE TITLE
Ich bitte um deine Hilfe

### ISSUE THREAD

**Issue by D3ltorohd** [madmartin/Jarolift_MQTT#18]
Hallo Martin,

ich würde mich riesig freuen wenn du mir helfen würdest deine Steuerung für Jarolift Motoren um zu setzten. Ich hoffe wir können irgendwie in Verbindung drehten. Ich habe von alle dem leider keinerlei Ahnung und bin eigentlich auf deine Hilfe angewiesen. Da du darin ein Spezialist zu sein scheinst dürfte es für dich um ein vielfaches einfacher sein als für mich.

Grüße

**Comment by madmartin** [comment]
Siehe http://www.bastelbudenbuben.de/forum/forum/jarolift-tdef-controller/
