### ISSUE TITLE
WebUI shutter page: edited channel names cannot be saved

### ISSUE THREAD

**Issue by madmartin** [madmartin/Jarolift_MQTT#2]
on the WebUI shutter page, while trying to edit, the "finish" button has no effect. This is a known problem with Firefox browser, and is known to work with Chrome/Chromium.

**Comment by sidddy** [comment]
Hi,

please check pull request #3 . At least it fixes the problem for me :-)

BR,
Sidddy

**Comment by madmartin** [comment]
Closed with PR #3 
Many thanks!
