### ISSUE TITLE
devicekey low and high always equal? Can not use LEARN 

### ISSUE THREAD

**Issue by bmaciag** [madmartin/Jarolift_MQTT#38]
Hi, I wanted to use the LEARN command to get started.
But in the Serial Console Im always just getting the same:
devicekey low: 0x805bxxxx // high: 0x805xxxx

Is this right? Since if I log the original remote control, they are always different.

**Comment by bmaciag** [comment]
Just changed the serial one more time and now they are different and its working fine

**Comment by madmartin** [comment]
I'm happy to hear it works!
